# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luca/PingPongProtocol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luca/PingPongProtocol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/PingPongProtocol/CMakeFiles /home/luca/PingPongProtocol/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/PingPongProtocol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PingPongProtocol_v1

# Build rule for target.
PingPongProtocol_v1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PingPongProtocol_v1
.PHONY : PingPongProtocol_v1

# fast build rule for target.
PingPongProtocol_v1/fast:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/build
.PHONY : PingPongProtocol_v1/fast

#=============================================================================
# Target rules for targets named PingPongProtocol_v2

# Build rule for target.
PingPongProtocol_v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PingPongProtocol_v2
.PHONY : PingPongProtocol_v2

# fast build rule for target.
PingPongProtocol_v2/fast:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/build
.PHONY : PingPongProtocol_v2/fast

#=============================================================================
# Target rules for targets named PingPongProtocol_v3

# Build rule for target.
PingPongProtocol_v3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PingPongProtocol_v3
.PHONY : PingPongProtocol_v3

# fast build rule for target.
PingPongProtocol_v3/fast:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/build
.PHONY : PingPongProtocol_v3/fast

src/Helper/ArgsParser.o: src/Helper/ArgsParser.cpp.o
.PHONY : src/Helper/ArgsParser.o

# target to build an object file
src/Helper/ArgsParser.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/ArgsParser.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/ArgsParser.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/ArgsParser.cpp.o
.PHONY : src/Helper/ArgsParser.cpp.o

src/Helper/ArgsParser.i: src/Helper/ArgsParser.cpp.i
.PHONY : src/Helper/ArgsParser.i

# target to preprocess a source file
src/Helper/ArgsParser.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/ArgsParser.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/ArgsParser.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/ArgsParser.cpp.i
.PHONY : src/Helper/ArgsParser.cpp.i

src/Helper/ArgsParser.s: src/Helper/ArgsParser.cpp.s
.PHONY : src/Helper/ArgsParser.s

# target to generate assembly for a file
src/Helper/ArgsParser.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/ArgsParser.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/ArgsParser.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/ArgsParser.cpp.s
.PHONY : src/Helper/ArgsParser.cpp.s

src/Helper/Logger.o: src/Helper/Logger.cpp.o
.PHONY : src/Helper/Logger.o

# target to build an object file
src/Helper/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/Logger.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/Logger.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/Logger.cpp.o
.PHONY : src/Helper/Logger.cpp.o

src/Helper/Logger.i: src/Helper/Logger.cpp.i
.PHONY : src/Helper/Logger.i

# target to preprocess a source file
src/Helper/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/Logger.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/Logger.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/Logger.cpp.i
.PHONY : src/Helper/Logger.cpp.i

src/Helper/Logger.s: src/Helper/Logger.cpp.s
.PHONY : src/Helper/Logger.s

# target to generate assembly for a file
src/Helper/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Helper/Logger.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Helper/Logger.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Helper/Logger.cpp.s
.PHONY : src/Helper/Logger.cpp.s

src/Message.o: src/Message.cpp.o
.PHONY : src/Message.o

# target to build an object file
src/Message.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Message.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Message.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Message.cpp.o
.PHONY : src/Message.cpp.o

src/Message.i: src/Message.cpp.i
.PHONY : src/Message.i

# target to preprocess a source file
src/Message.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Message.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Message.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Message.cpp.i
.PHONY : src/Message.cpp.i

src/Message.s: src/Message.cpp.s
.PHONY : src/Message.s

# target to generate assembly for a file
src/Message.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Message.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Message.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Message.cpp.s
.PHONY : src/Message.cpp.s

src/Peer/Peer.o: src/Peer/Peer.cpp.o
.PHONY : src/Peer/Peer.o

# target to build an object file
src/Peer/Peer.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer.cpp.o
.PHONY : src/Peer/Peer.cpp.o

src/Peer/Peer.i: src/Peer/Peer.cpp.i
.PHONY : src/Peer/Peer.i

# target to preprocess a source file
src/Peer/Peer.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer.cpp.i
.PHONY : src/Peer/Peer.cpp.i

src/Peer/Peer.s: src/Peer/Peer.cpp.s
.PHONY : src/Peer/Peer.s

# target to generate assembly for a file
src/Peer/Peer.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer.cpp.s
.PHONY : src/Peer/Peer.cpp.s

src/Peer/Peer_p.o: src/Peer/Peer_p.cpp.o
.PHONY : src/Peer/Peer_p.o

# target to build an object file
src/Peer/Peer_p.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_p.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_p.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_p.cpp.o
.PHONY : src/Peer/Peer_p.cpp.o

src/Peer/Peer_p.i: src/Peer/Peer_p.cpp.i
.PHONY : src/Peer/Peer_p.i

# target to preprocess a source file
src/Peer/Peer_p.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_p.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_p.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_p.cpp.i
.PHONY : src/Peer/Peer_p.cpp.i

src/Peer/Peer_p.s: src/Peer/Peer_p.cpp.s
.PHONY : src/Peer/Peer_p.s

# target to generate assembly for a file
src/Peer/Peer_p.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_p.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_p.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_p.cpp.s
.PHONY : src/Peer/Peer_p.cpp.s

src/Peer/Peer_pp.o: src/Peer/Peer_pp.cpp.o
.PHONY : src/Peer/Peer_pp.o

# target to build an object file
src/Peer/Peer_pp.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_pp.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_pp.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_pp.cpp.o
.PHONY : src/Peer/Peer_pp.cpp.o

src/Peer/Peer_pp.i: src/Peer/Peer_pp.cpp.i
.PHONY : src/Peer/Peer_pp.i

# target to preprocess a source file
src/Peer/Peer_pp.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_pp.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_pp.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_pp.cpp.i
.PHONY : src/Peer/Peer_pp.cpp.i

src/Peer/Peer_pp.s: src/Peer/Peer_pp.cpp.s
.PHONY : src/Peer/Peer_pp.s

# target to generate assembly for a file
src/Peer/Peer_pp.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/Peer/Peer_pp.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/Peer/Peer_pp.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/Peer/Peer_pp.cpp.s
.PHONY : src/Peer/Peer_pp.cpp.s

src/TopologyGen.o: src/TopologyGen.cpp.o
.PHONY : src/TopologyGen.o

# target to build an object file
src/TopologyGen.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/TopologyGen.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/TopologyGen.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/TopologyGen.cpp.o
.PHONY : src/TopologyGen.cpp.o

src/TopologyGen.i: src/TopologyGen.cpp.i
.PHONY : src/TopologyGen.i

# target to preprocess a source file
src/TopologyGen.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/TopologyGen.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/TopologyGen.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/TopologyGen.cpp.i
.PHONY : src/TopologyGen.cpp.i

src/TopologyGen.s: src/TopologyGen.cpp.s
.PHONY : src/TopologyGen.s

# target to generate assembly for a file
src/TopologyGen.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/TopologyGen.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/TopologyGen.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/TopologyGen.cpp.s
.PHONY : src/TopologyGen.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/main.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/main.cpp.o
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/main.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/main.cpp.i
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PingPongProtocol_v1.dir/build.make CMakeFiles/PingPongProtocol_v1.dir/src/main.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v2.dir/build.make CMakeFiles/PingPongProtocol_v2.dir/src/main.cpp.s
	$(MAKE) -f CMakeFiles/PingPongProtocol_v3.dir/build.make CMakeFiles/PingPongProtocol_v3.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PingPongProtocol_v1"
	@echo "... PingPongProtocol_v2"
	@echo "... PingPongProtocol_v3"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Helper/ArgsParser.o"
	@echo "... src/Helper/ArgsParser.i"
	@echo "... src/Helper/ArgsParser.s"
	@echo "... src/Helper/Logger.o"
	@echo "... src/Helper/Logger.i"
	@echo "... src/Helper/Logger.s"
	@echo "... src/Message.o"
	@echo "... src/Message.i"
	@echo "... src/Message.s"
	@echo "... src/Peer/Peer.o"
	@echo "... src/Peer/Peer.i"
	@echo "... src/Peer/Peer.s"
	@echo "... src/Peer/Peer_p.o"
	@echo "... src/Peer/Peer_p.i"
	@echo "... src/Peer/Peer_p.s"
	@echo "... src/Peer/Peer_pp.o"
	@echo "... src/Peer/Peer_pp.i"
	@echo "... src/Peer/Peer_pp.s"
	@echo "... src/TopologyGen.o"
	@echo "... src/TopologyGen.i"
	@echo "... src/TopologyGen.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

